SELECT YEAR(SALES_DATE) AS YEAR
     , MONTH(SALES_DATE) AS MONTH
     , GENDER
     , COUNT(DISTINCT U.USER_ID) AS USERS
FROM USER_INFO AS U
         JOIN ONLINE_SALE AS O
              ON U.USER_ID = O.USER_ID
WHERE U.GENDER IS NOT NULL
GROUP BY YEAR(SALES_DATE)
       , MONTH(SALES_DATE)
       , GENDER